# ______               _           _
# | ___ \             | |         | |
# | |_/ /  ___    ___ | | __  ___ | |_
# |    /  / _ \  / __|| |/ / / _ \| __|
# | |\ \ | (_) || (__ |   < |  __/| |_
# \_| \_| \___/  \___||_|\_\ \___| \__|
#  _____                _      _
# /  __ \              | |    | |
# | /  \/  ___    ___  | |  __| |  ___  __      __ _ __
# | |     / _ \  / _ \ | | / _` | / _ \ \ \ /\ / /| '_ \
# | \__/\| (_) || (_) || || (_| || (_) | \ V  V / | | | |
# \____/ \___/  \___/ |_| \__,_| \___/   \_/\_/  |_| |_|

# 서버를 재시작하지 않고 config파일을 저장하려면 [/firework reload]명령어를 사용하세요.

# ─────────────────────────────────────────────────────────────────────────────

# cooldown: 폭죽로켓 사용 쿨다운을 지정합니다. (단위: 초) [기본값: 12]
# 분 이상의 숫자를 입력해도 초로 표시됩니다.
# <! 숫자만 입력하세요>
cooldown: 12

# message.cooldowwn: 폭죽로켓 사용 쿨다운이 남았을 때의 메시지를 지정합니다.
# [seconds] 를 사용하여 남은 시간을 표시할 수 있습니다.
# §(색상코드)를 사용해서 색상을 사용할 수 있습니다.
message:
  cooldown: '§c아직 쿨다운이 [seconds]초 남았습니다.'